version: '3.8'

services:

  todo-app:
    image: todo-app
    container_name: todo-app
    build:
      context: Dockerfile
      dockerfile: Dockerfile

    depends_on:
      - todo-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-db:5432/tododb
      - SPRING_DATASOURCE_USERNAME=onur
      - SPRING_DATASOURCE_PASSWORD=onur58

  todo-db:
    image: postgres
    container_name: todo-db
    volumes:
      - postgres-todo-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: onur
      POSTGRES_PASSWORD: onur58
    ports:
      - "5858:5432"


volumes:
  postgres-todo-data:
    name: postgres-todo-data